[functions]
    external_node_modules = ["express", "node-telegram-bot-api"]
    node_bundler = "esbuild"
    directory = "netlify/func/"

[build]
    base = "/"
    command = "npm run build"
    functions = "netlify/func/"

[dev]
    framework = "#custom"
    command = "npm run start"
    port = 8888
    targetPort = 8081
    publish = "."

[context.production.environment]
    NODE_ENV = "production"
    PORT = "8081"
    URL = "https://gs-bot.netlify.app"
    SELENIUM_URL = "https://reisinfo.rrreis.nl/nl/rrreis/lijnen/4304/dienstregeling/heen"
    TOKEN = "8187510934:AAGRtzid0wOsfX7F21QMCbD6cU5k4iKPrTw"

[context.dev.environment]
    NODE_ENV = "development"
    URL = "https://gs-bot.netlify.app"
    SELENIUM_URL = "https://reisinfo.rrreis.nl/nl/rrreis/lijnen/4304/dienstregeling/heen"
    TOKEN = "8187510934:AAGRtzid0wOsfX7F21QMCbD6cU5k4iKPrTw"
    PORT = "8081"

[[redirects]]
    force = true
    from = "/*"
    to = "/.netlify/func/index"
    status = 200
