const DIRECTIONS = { ZWOLLE: 'zwolle', APELDOORN: 'apeldoorn' };
const WEEKDAYS = {
    SUNDAY: 0,
    MONDAY: 1,
    TUESDAY: 2,
    WEDNESDAY: 3,
    THURSDAY: 4,
    FRIDAY: 5,
    SATURDAY: 6,
};

const BUS_STOPS = [
    'Apeldoorn, Station',
    'Zwolle, Station',
    'Apeldoorn, Marktplein',
    'Apeldoorn, Oranjepark/Regentesselaan',
    'Apeldoorn, Grote Kerk',
    'Apeldoorn, Bosweg',
    'Apeldoorn, Gedenknaald',
    'Apeldoorn, Van Haeftenkazerne',
    'Wenum, Wieselseweg',
    'Wenum, Papegaaiweg',
    'Wenum, De Haere',
    'Vaassen, Vaassen-Zuid',
    'Vaassen, Oosterhof',
    'Vaassen, Centrum',
    'Vaassen, Vaassen-Noord',
    'Emst, Handelsebrug',
    'Emst, Hezeplein',
    'Emst, Oranjeweg',
    'Epe, Klaarbeek',
    'Epe, Sint Jorisweg',
    'Epe, Diepenweg',
    'Epe, Centrum',
    'Epe, Politiebureau',
    'Heerde, Transferium Horsthoek',
    'Heerde, Eperweg',
    'Heerde, Brinklaan',
    'Heerde, Molenkampweg',
    'Heerde, Zwolseweg',
    'Heerde, Dreefseweg/Isala',
    'Wapenveld, Nachtegaalweg',
    'Wapenveld, Molenweg',
    'Wapenveld, Parkweg',
    'Wapenveld, Ir R.R. v/d Zeelaan',
    'Hattem, Pompstation',
    'Hattem, Zuid',
    'Hattem, Centrum',
    'Hattem, Noord',
    'Hattem, IJsselbrug',
    'Zwolle, Het Engelse Werk',
    'Zwolle, Katwolderplein/Centrum',
    'Zwolle, Oranje Nassaulaan',
    'Zwolle, Koningin Wilhelminastraat',
];

module.exports = { DIRECTIONS, BUS_STOPS, WEEKDAYS };
