const DIRECTIONS = { ZWOLLE: 'zwolle', APELDOORN: 'apeldoorn' };
const WEEKDAYS = {
    SUNDAY: 0,
    MONDAY: 1,
    TUESDAY: 2,
    WEDNESDAY: 3,
    THURSDAY: 4,
    FRIDAY: 5,
    SATURDAY: 6,
};

const BUS_STOPS = [
    'Apeldoorn, Station',
    'Zwolle, Station',
    'Marktplein',
    'Oranjepark/Regentesselaan',
    'Grote Kerk',
    'Bosweg',
    'Gedenknaald',
    'Van Haeftenkazerne',
    'Wieselseweg',
    'Papegaaiweg',
    'De Haere',
    'Vaassen-Zuid',
    'Oosterhof',
    'Vaassen Centrum',
    'Vaassen-Noord',
    'Handelsebrug',
    'Hezeplein',
    'Oranjeweg',
    'Klaarbeek',
    'Sint Jorisweg',
    'Diepenweg',
    'Centrum',
    'Politiebureau',
    'Transferium Horsthoek',
    'Eperweg',
    'Brinklaan',
    'Molenkampweg',
    'Zwolseweg',
    'Dreefseweg/Isala',
    'Nachtegaalweg',
    'Molenweg',
    'Parkweg',
    'Ir R.R. v/d Zeelaan',
    'Hattem Pompstation',
    'Hattem Zuid',
    'Hattem Centrum',
    'Hattem Noord',
    'IJsselbrug',
    'Het Engelse Werk',
    'Katwolderplein/Centrum',
    'Oranje Nassaulaan',
    'Koningin Wilhelminastraat',
];

module.exports = { DIRECTIONS, BUS_STOPS, WEEKDAYS };
